config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'root_path' => 'static_pages#home'
  get  'history' => 'static_pages#history'
  get 'people' => 'static_pages#people'
  get 'attractions' => 'static_pages#attractions'
  get 'comments' => 'messages#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'tweet' => 'static_pages#posts'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages do
    resources :comments
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order("created_at DESC")
  end
  
  def show
    @message = Message.find(params[:id])
  end
    
  def new
    @message = current_user.messages.build
  end
  
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:success] = "Message created!"
      redirect_to comments_path
    end
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to comments_path
  end
  
  private
  
    def message_params
      params.require(:message).permit(:title, :description)
    end
    
    def find_message
      @message = Message.find(params[:id])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<li id="message-<%= message.id %>">
  <%= link_to gravatar_for(message.user, size: 50), message.user %>
  <span class="user"><%= link_to message.user.name, message.user %></span>
  <span class="content">
    <%= message.description %>
  </span>
  
  <span class="timestamp">
    Posted <%= time_ago_in_words(message.created_at) %> ago.
    <% if current_user?(message.user) %>
      <%= link_to "delete", message, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </span>
  <br><br><br>
</li>

app/views/messages/_message_form.html.erb
<div class="message_form">

    
    <%= form_for @message do |f| %>
    <%= render 'shared/error_messages', object: f.object %>      
      <%= f.label :message_title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <%= f.submit "Create message", class: "btn btn-primary" %>
      
    <% end %>

</div>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'message_form' %>

app/views/messages/index.html.erb
<% provide(:title, "Forum") %>

<h3> Welcome to the forum! Please feel free to share your Garrett County experiences with others here!</h3>
<% if !logged_in? %>
      <h4>You must sign up or sign in to post or view messages.  Click on the link below to sign up or log in via the navigation bar.</h4>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-primary" %>
      <% end %>
    <% if logged_in? &&  @messages.count ==  0 %>
      <%= link_to "New Message", new_message_path, class: "btn btn-primary" %>
    <% elsif logged_in? && @messages.count > 0 %> 
      <% @messages.each do |message| %>
	<div class="col-md-4">
		<div class="message">
			<h2 class="message-title"><%= message.title %></h2>
			<%= link_to "View Message", message, class: "btn btn-default" %>
			<%= link_to "New Message", new_message_path, class: "btn btn-default" %>
		</div>
	</div>
<% end %>
   
<% end %>

app/views/messages/new.html.erb
<% provide(:title, "New Message") %>
<div class="col-md-8 col-md-offset-2">
	<h1 class="new-msg-header">New Message</h1>
	<%= render 'message_form' %>
</div>

app/views/messages/show.html.erb
<% provide(:title, "Message") %>
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Posted by <%= @message.user.name %> <%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-desc"><%= @message.description %></p>

		<h3 class="comment-section-header">Comments:</h3>
		<!-- renders the _comment.html.erb partial file. -->
		<p><%= render @message.comments %></p>

		<h3 class="reply-to-msg">Reply to Message:</h3>
		<!-- renders the comments form -->
		<%= render 'comments/form' %>


		
		<div class="links btn-group">
			<%= link_to "Back", messages_path, class: "btn btn-default" %>
			<% if @message.user_id == current_user.id %>
				<%= link_to "Edit Message", edit_message_path(@message), class: "btn btn-default" %>
				<%= link_to "Delete Message", message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>



    
        