config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'root_path' => 'static_pages#home'
  get  'history' => 'static_pages#history'
  get 'people' => 'static_pages#people'
  get 'attractions' => 'static_pages#attractions'
  get 'comments' => 'messages#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'tweet' => 'static_pages#posts'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]
  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id
    
    if @comment.save
      flash[:success] = "Comment created!"
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end
  
  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end
  
  def edit
  end
  
  private
    
    def comment_params
      params.require(:comment).permit(:content)
    end
    
    def find_message
      @message = Message.find(params[:message_id])
    end
      
    def find_comment
      @comment = @message.comments.find(params[:id])
    end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
		<% if comment.user_id == current_user.id %>
			<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
			<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
    <%= form_for [@message, @message.comments.build] do |f| %>
    <%= render 'shared/error_messages', object: f.object %>      
      <%= f.label :comment %>
      <%= f.text_area :content, class: 'form-control' %>
      <%= f.submit "Reply", class: "btn btn-primary" %>
      
    <% end %>

app/views/comments/edit.html.erb
<% provide(:title, "Edit Comments") %>

<h3>Edit Comments</h3>
<%= form_for [@message, @comment] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :content, class: 'form-control' %>
  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>