config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'root_path' => 'static_pages#home'
  get  'history' => 'static_pages#history'
  get 'people' => 'static_pages#people'
  get 'attractions' => 'static_pages#attractions'
  get 'comments' => 'messages#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'tweet' => 'static_pages#posts'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages do
    resources :comments
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Author: Jason Snyder
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav id = "nav">
      <ul class="nav navbar-nav navbar-right">
      <ul id="navigation">
        
        <li><a href="#" class="first">Navigation</a>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "History", history_path %></li>
            <li><%= link_to "Famous Visitors", people_path %></li>
            <li><%= link_to "Attractions", attractions_path %></li>
            <li><%= link_to "Forum", messages_path %></li>
          </ul>
          <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Tweets", tweet_path %></li>
              <li><a href="#" class="second">Account</a>
                <ul>
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path %>
                  </li>
                  </li>
                  </ul>
                </ul>
              </li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
        </li>
      </ul>
      
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
    <META HTTP-EQUIV="Expires" CONTENT="0">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'slider', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'count.py', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
     <div class="container">
    <%= render 'layouts/header' %>
   
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
</div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>